server:
  port: 8080

spring:
  data:
    mongodb:
      database: stocks-api
      port: 27017
      host: localhost

#okta:
#  oauth2:
#    issuer: https://{yourOktaDomain}/oauth2/default
#    client-id: {yourClientId}
#    client-secret: {yourClientSecret}