server:
  port: 8080
  error:
    include-message: always

spring:
  data:
    mongodb:
      auto-index-creation: true
      database: stocks
      port: 27017
      host: localhost

stocks:
  client:
    apiKey: MJJEK8TIS2ZZ7XSL
    baseUrl: https://www.alphavantage.co/query

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.keithcaff: DEBUG

okta:
  oauth2:
    issuer: https://dev-8153053.okta.com/oauth2/default
#    client-id: YOUR_CLIENT
#    client-secret: YOUR_CLIENT_SECRET
